# Generated by Django 4.2.6 on 2023-10-08 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 18, 30, 52, 979958, tzinfo=datetime.timezone.utc)),
        ),
    ]
